#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-lz4
Version  : 3.1.10
Release  : 1
URL      : https://files.pythonhosted.org/packages/53/31/df54b869e4a3a97eb6735c7d0853758124dfbd61dd9e9e1c7b5e72fd55b4/lz4-3.1.10.tar.gz
Source0  : https://files.pythonhosted.org/packages/53/31/df54b869e4a3a97eb6735c7d0853758124dfbd61dd9e9e1c7b5e72fd55b4/lz4-3.1.10.tar.gz
Summary  : LZ4 Bindings for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-lz4-license = %{version}-%{release}
Requires: pypi-lz4-python = %{version}-%{release}
Requires: pypi-lz4-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(future)
BuildRequires : pypi(pkgconfig)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(tox)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
==========
python-lz4
==========
Status
======
.. image:: https://travis-ci.org/python-lz4/python-lz4.svg?branch=master
:target: https://travis-ci.org/python-lz4/python-lz4
:alt: Build Status

%package license
Summary: license components for the pypi-lz4 package.
Group: Default

%description license
license components for the pypi-lz4 package.


%package python
Summary: python components for the pypi-lz4 package.
Group: Default
Requires: pypi-lz4-python3 = %{version}-%{release}

%description python
python components for the pypi-lz4 package.


%package python3
Summary: python3 components for the pypi-lz4 package.
Group: Default
Requires: python3-core
Provides: pypi(lz4)
Requires: pypi(future)
Requires: pypi(tox)

%description python3
python3 components for the pypi-lz4 package.


%prep
%setup -q -n lz4-3.1.10
cd %{_builddir}/lz4-3.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641578453
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-lz4
cp %{_builddir}/lz4-3.1.10/LICENSE %{buildroot}/usr/share/package-licenses/pypi-lz4/ec224694848d1d4a6709ac3dc241b1935a4444e3
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-lz4/ec224694848d1d4a6709ac3dc241b1935a4444e3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
