#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-lz4
Version  : 4.0.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/36/bf/fa0380f3bfc4a37ebde793709b70666485835355f666d72576857f7c5269/lz4-4.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/bf/fa0380f3bfc4a37ebde793709b70666485835355f666d72576857f7c5269/lz4-4.0.1.tar.gz
Summary  : LZ4 Bindings for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-lz4-filemap = %{version}-%{release}
Requires: pypi-lz4-lib = %{version}-%{release}
Requires: pypi-lz4-license = %{version}-%{release}
Requires: pypi-lz4-python = %{version}-%{release}
Requires: pypi-lz4-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(future)
BuildRequires : pypi(pkgconfig)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(tox)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
==========
python-lz4
==========
Status
======
.. image:: https://travis-ci.org/python-lz4/python-lz4.svg?branch=master
:target: https://travis-ci.org/python-lz4/python-lz4
:alt: Build Status

%package filemap
Summary: filemap components for the pypi-lz4 package.
Group: Default

%description filemap
filemap components for the pypi-lz4 package.


%package lib
Summary: lib components for the pypi-lz4 package.
Group: Libraries
Requires: pypi-lz4-license = %{version}-%{release}
Requires: pypi-lz4-filemap = %{version}-%{release}

%description lib
lib components for the pypi-lz4 package.


%package license
Summary: license components for the pypi-lz4 package.
Group: Default

%description license
license components for the pypi-lz4 package.


%package python
Summary: python components for the pypi-lz4 package.
Group: Default
Requires: pypi-lz4-python3 = %{version}-%{release}

%description python
python components for the pypi-lz4 package.


%package python3
Summary: python3 components for the pypi-lz4 package.
Group: Default
Requires: pypi-lz4-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(lz4)
Requires: pypi(future)
Requires: pypi(tox)

%description python3
python3 components for the pypi-lz4 package.


%prep
%setup -q -n lz4-4.0.1
cd %{_builddir}/lz4-4.0.1
pushd ..
cp -a lz4-4.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1653342349
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-lz4
cp %{_builddir}/lz4-4.0.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-lz4/ec224694848d1d4a6709ac3dc241b1935a4444e3
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-lz4

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-lz4/ec224694848d1d4a6709ac3dc241b1935a4444e3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
